/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  ButtonEvent,
  ButtonType,
  ControlSize,
} from './components/health-button/health-button.types';

export namespace Components {
  interface HealthButton {
    'disabled': boolean;
    'name': string;
    'size': ControlSize;
    'type': ButtonType;
  }
  interface HealthDropdown {
    'open': boolean;
  }
}

declare global {


  interface HTMLHealthButtonElement extends Components.HealthButton, HTMLStencilElement {}
  var HTMLHealthButtonElement: {
    prototype: HTMLHealthButtonElement;
    new (): HTMLHealthButtonElement;
  };

  interface HTMLHealthDropdownElement extends Components.HealthDropdown, HTMLStencilElement {}
  var HTMLHealthDropdownElement: {
    prototype: HTMLHealthDropdownElement;
    new (): HTMLHealthDropdownElement;
  };
  interface HTMLElementTagNameMap {
    'health-button': HTMLHealthButtonElement;
    'health-dropdown': HTMLHealthDropdownElement;
  }
}

declare namespace LocalJSX {
  interface HealthButton extends JSXBase.HTMLAttributes<HTMLHealthButtonElement> {
    'disabled'?: boolean;
    'name'?: string;
    'onHealthButton'?: (event: CustomEvent<ButtonEvent>) => void;
    'size'?: ControlSize;
    'type'?: ButtonType;
  }
  interface HealthDropdown extends JSXBase.HTMLAttributes<HTMLHealthDropdownElement> {
    'open'?: boolean;
  }

  interface IntrinsicElements {
    'health-button': HealthButton;
    'health-dropdown': HealthDropdown;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


